version: 0.2
phases:
  install:
      commands:
        - npm install -g serverless

  DeployBackendCognito:
     commands:
          - cd sls-demo-backend-cognito
          - serverless deploy

  DeployBackend:
     commands:
          - cd sls-demo-backend
          - serverless deploy
