version: 0.1
phases:
  install:
      commands:
        - npm install -g serverless
  build:
     commands:
          - cd /serverless-cognito-auth
          - serverless deploy --stage dev us-east-1 --verbose
